language: objective-c
osx_image: xcode9.2
env:
  - DESTINATION="arch=x86_64"                    PLATFORM=Mac
  - DESTINATION="OS=11.2,name=iPhone SE"         PLATFORM=iOS
  - DESTINATION="OS=10.3.1,name=iPhone SE"       PLATFORM=iOS
  - DESTINATION="OS=9.3,name=iPhone SE"          PLATFORM=iOS
  - DESTINATION="OS=8.4,name=iPhone 4s"          PLATFORM=iOS
  - DESTINATION="OS=11.2,name=Apple TV"          PLATFORM=tvOS
  - DESTINATION="OS=10.2,name=Apple TV 1080p"    PLATFORM=tvOS
  - DESTINATION="OS=9.0,name=Apple TV 1080p"     PLATFORM=tvOS
before_install:
  - carthage bootstrap --cache-builds --no-use-binaries --platform $PLATFORM --verbose
install:
  - xcodebuild -scheme PMKSystemConfiguration -destination "$DESTINATION" build-for-testing
script:
  - xcodebuild -scheme PMKSystemConfiguration -destination "$DESTINATION" test
